[package]
name = "bevy-2048"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
#bevy = { version = "0.15", features = ["dynamic_linking", "wayland"] }
bevy = { version = "0.15" } 
bevy_aseprite_ultra = "0.4.1"
bevy_tweening = "0.12"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
